"""Dashboard rendering skill.

Produces self-contained HTML for persistent dashboards saved into the user's
Obsidian vault at `/obsidian/_dashboards/<topic>.html`. Dashboards are
updated in place (one file per topic, never duplicated).

Usage:
    from app.skills.dashboard import Dashboard, KpiCard, Section

    html = Dashboard(
        title="SF Apartment Search",
        subtitle_html='Last updated <code>2026-05-17 10:00 UTC</code>',
        kpis=[KpiCard("Total candidates", "2"), ...],
        sections=[Section("Solo track", "<table>...</table>"), ...],
        source="hermes-agent listings DB",
    ).render()
"""
from __future__ import annotations

from dataclasses import dataclass, field

from ._style import BASE_CSS, html_escape


@dataclass
class KpiCard:
    label: str
    value: str  # already-rendered, may contain numbers or short text


@dataclass
class Section:
    heading: str
    body_html: str  # caller is responsible for escaping content


@dataclass
class Dashboard:
    title: str
    subtitle_html: str = ""        # rendered HTML for the meta line
    kpis: list[KpiCard] = field(default_factory=list)
    sections: list[Section] = field(default_factory=list)
    source: str = ""               # short description of data origin
    max_width_px: int = 1200

    def render(self) -> str:
        kpi_blocks = "".join(
            f'<div class="card"><div class="label">{html_escape(k.label)}</div>'
            f'<div class="value">{k.value}</div></div>'
            for k in self.kpis
        )
        kpi_section = f'<div class="grid">{kpi_blocks}</div>' if kpi_blocks else ""

        body_sections = "\n".join(
            f"<h2>{html_escape(s.heading)}</h2>{s.body_html}" for s in self.sections
        )

        meta = f'<div class="meta">{self.subtitle_html}</div>' if self.subtitle_html else ""
        source = (
            f'<div class="source">Source: {html_escape(self.source)}. '
            "Generated by hermes-agent.</div>"
            if self.source
            else ""
        )

        return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html_escape(self.title)} — Dashboard</title>
<style>
body {{ max-width: {self.max_width_px}px; }}
{BASE_CSS}
</style></head><body>
<h1>{html_escape(self.title)}</h1>
{meta}
{kpi_section}
{body_sections}
{source}
</body></html>
"""
