"""Report rendering skill.

Produces self-contained HTML for one-off, dated reports saved into the user's
Obsidian vault inside the relevant PARA folder, e.g.
`/obsidian/Projects/<Project>/<YYYY-MM-DD-title>.html`. Each report is a
point-in-time artifact — never overwrite prior reports.

Usage:
    from app.skills.report import Report

    html = Report(
        title="SF Apartment Findings",
        iso_date="2026-05-17",
        project_or_area="SF Apartment Search",
        index_link_html='<a href="./SF Apartment Search.md">project notes</a>',
        tldr_html="<p>2 candidates active...</p>",
        findings_html="<ul>...</ul>",
        recommendations_html="<ol>...</ol>",
        source="hermes-agent listings DB",
    ).render()
"""
from __future__ import annotations

from dataclasses import dataclass

from ._style import BASE_CSS, html_escape


@dataclass
class Report:
    title: str
    iso_date: str
    project_or_area: str
    index_link_html: str = ""        # rendered <a> link back to project/area
    tldr_html: str = ""              # short TL;DR (1-3 sentences)
    findings_html: str = ""          # what was learned
    options_html: str = ""           # options & trade-offs
    recommendations_html: str = ""   # ordered list of actions
    open_questions_html: str = ""    # what's still unknown
    extra_sections: list[tuple[str, str]] = None   # [(heading, html), ...]
    source: str = ""
    max_width_px: int = 880

    def render(self) -> str:
        def section(heading: str, body: str) -> str:
            if not body or not body.strip():
                return ""
            return f"<h2>{html_escape(heading)}</h2>{body}"

        extras = ""
        if self.extra_sections:
            extras = "\n".join(section(h, b) for h, b in self.extra_sections)

        meta_parts = [self.iso_date, html_escape(self.project_or_area)]
        if self.index_link_html:
            meta_parts.append(self.index_link_html)
        meta = " · ".join(p for p in meta_parts if p)

        tldr = (
            f'<div class="tldr"><strong>TL;DR.</strong> {self.tldr_html}</div>'
            if self.tldr_html
            else ""
        )
        source = (
            f'<div class="source">Source: {html_escape(self.source)}. '
            f"Generated by hermes-agent at {self.iso_date}.</div>"
            if self.source
            else ""
        )

        return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html_escape(self.title)} — Report ({self.iso_date})</title>
<style>
body {{ max-width: {self.max_width_px}px; line-height: 1.6; }}
{BASE_CSS}
</style></head><body>
<h1>{html_escape(self.title)}</h1>
<div class="meta">{meta}</div>
{tldr}
{section("Findings", self.findings_html)}
{section("Options & trade-offs", self.options_html)}
{section("Recommended actions", self.recommendations_html)}
{section("Open questions", self.open_questions_html)}
{extras}
{source}
</body></html>
"""
